### PR TITLE
chore: placeables max supply updates

### PR DESCRIPTION
**Pull request by ghost**
## Description

Placeables max supply updates.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

-   [X] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
-   [ ] ~added `!` to the type prefix if API or client breaking change~
-   [ ] ~provided a link to the relevant issue or specification~
-   [X] included the necessary unit and integration tests
-   [X] code is adequately commented
-   [ ] ~updated the relevant documentation or specification~
-   [X] reviewed "Files changed" and left comments if necessary
-   [X] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

-   [x] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
-   [ ] ~confirmed `!` in the type prefix if API or client breaking change~
-   [ ] ~confirmed all author checklist items have been addressed~
-   [x] reviewed service design and naming
-   [ ] ~reviewed documentation is accurate~
-   [x] reviewed tests and test coverage
-   [x] manually tested (if applicable)

### CODE REVIEW

**Comment by ghost** [comment]
Ensure the following env vars are set:

```
DEPLOYER_PRIVATE_KEY
RPC_URL
```

The `DEPLOYER_PRIVATE_KEY` can be set to any key (if you require an RPC endpoint for mainnet, please tag me).

To then generate the calldata, run:

```
npm run deploy:mainnet 
```

Output:


```
schedule batch calldata with  1  action
  0x8f2a0bb000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000290efc7aba8ae3bcf080025ecc929f1055d8e69fd809f5efccf815289b32f903000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002c154ae907652a1a9939dbe0622915111816942c00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000016200000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000

execute batch calldata
  0xe38335e500000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000290efc7aba8ae3bcf080025ecc929f1055d8e69fd809f5efccf815289b32f90300000000000000000000000000000000000000000000000000000000000000010000000000000000000000002c154ae907652a1a9939dbe0622915111816942c00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000016200000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000
```

**Comment by KBryan** [comment]
schedule batch calldata with  1  action
  ```  0x8f2a0bb000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000290efc7aba8ae3bcf080025ecc929f1055d8e69fd809f5efccf815289b32f903000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002c154ae907652a1a9939dbe0622915111816942c00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000016200000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000
 ```
  warping to 1713324621
  execute batch calldata
 ```
0xe38335e500000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000290efc7aba8ae3bcf080025ecc929f1055d8e69fd809f5efccf815289b32f90300000000000000000000000000000000000000000000000000000000000000010000000000000000000000002c154ae907652a1a9939dbe0622915111816942c00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000016200000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000
```

**Review by KBryan — APPROVED** [review]
lgtm

**Review by ElliotFriedman — APPROVED** [review]
LGTM!

**Pull request merged**
