### PR TITLE
chore: wearables max supply updates

### PR DESCRIPTION
**Pull request by ghost**
## Description

Wearables max supply updates.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

-   [X] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
-   [ ] ~added `!` to the type prefix if API or client breaking change~
-   [ ] ~provided a link to the relevant issue or specification~
-   [X] included the necessary unit and integration tests
-   [X] code is adequately commented
-   [ ] ~updated the relevant documentation or specification~
-   [X] reviewed "Files changed" and left comments if necessary
-   [x] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

-   [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
-   [ ] confirmed `!` in the type prefix if API or client breaking change
-   [ ] confirmed all author checklist items have been addressed
-   [ ] reviewed service design and naming
-   [ ] reviewed documentation is accurate
-   [ ] reviewed tests and test coverage
-   [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by ghost** [comment]
Ensure the following env vars are set:

```
DEPLOYER_PRIVATE_KEY
RPC_URL
```

The `DEPLOYER_PRIVATE_KEY` can be set to any key (if you require an RPC endpoint for mainnet, please tag me).

To then generate the calldata, run:

```
npm run deploy:mainnet 
```

Output:


```
schedule batch calldata with  12  actions
  0x8f2a0bb000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000f5f37b99f0748d954a3c52766e2fc336a694b85a04dc82b7f2fa91817c1f207d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002800000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000068000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004d00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004e00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004f00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005100000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005300000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005500000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005600000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005700000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000

execute batch calldata
  0xe38335e500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000003e00000000000000000000000000000000000000000000000000000000000000000f5f37b99f0748d954a3c52766e2fc336a694b85a04dc82b7f2fa91817c1f207d000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002800000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000068000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004d00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004e00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004f00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005100000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005300000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005500000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005600000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005700000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000
```

**Comment by prat-gpt** [comment]
Please add the new zip to the `BootstrapTestnet` script as well. @intl-man

**Comment by ghost** [comment]
> Please add the new zip to the `BootstrapTestnet` script as well. @intl-man

Done @prateek105

**Review by prat-gpt — APPROVED** [review]
lgtm

**Comment by KBryan** [comment]
lgtm

  schedule batch calldata with  12  actions
  
```
0x8f2a0bb000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000f5f37b99f0748d954a3c52766e2fc336a694b85a04dc82b7f2fa91817c1f207d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002800000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000068000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004d00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004e00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004f00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005100000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005300000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005500000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005600000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005700000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000
 ```
  warping to 1713451278
  execute batch calldata
  ```
0xe38335e500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000003e00000000000000000000000000000000000000000000000000000000000000000f5f37b99f0748d954a3c52766e2fc336a694b85a04dc82b7f2fa91817c1f207d000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000792e36c772f6da6280fa43159792f89e7444cf18000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002800000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000068000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004d00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004e00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000004f00000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005100000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005300000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005500000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005600000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005700000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044ccb3cf07000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000
```

**Review by KBryan — APPROVED** [review]
lgtm

**Pull request merged**
